<?php

namespace eclore\userBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AssociationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssociationRepository extends EntityRepository
{
}
