<?php

namespace eclore\userBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NewsPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsPostRepository extends EntityRepository
{

public function getCurrentNewsPosts()
    {
        $qb = $this->_em->createQueryBuilder();
 
        $qb->select('a')
       ->from('ecloreuserBundle:NewsPost', 'a')
       ->where('a.endDate > :datecourant')
         ->setParameter('datecourant', new \Datetime(date('Y-m-d')))
       ->orderBy('a.id', 'DESC');
 
        return $qb->getQuery()
               ->getResult();
    }

}
