<?php

namespace eclore\userBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends EntityRepository
{
    public function findByReceiverAndType($user, $type) 
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('n')
                ->from($this->_entityName, 'n')
                ->where('n.type = :type')
                ->setParameter('type', $type)
                ->join('n.receivers', 'r')
                ->andWhere($qb->expr()->in('r.id',$user->getId()))
                ->orderBy('n.initDate', 'DESC');
        return $qb->getQuery()->getResult();
    }
    
    public function findBySenderAndType($user, $type) 
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('n')
                ->from($this->_entityName, 'n')
                ->where('n.type = :type')
                ->setParameter('type', $type)
                ->join('n.sender', 'r')
                ->andWhere('r.id = :id')
                ->setParameter('id', $user->getId())
                ->orderBy('n.initDate', 'DESC');
        return $qb->getQuery()->getResult();
    }
    
    public function contactRequested($user1, $user2)
    {
        $rep = $this->_em->getRepository('ecloreuserBundle:Notification');           
        $ct_not_recby1 = $rep->findByReceiverAndType($user1, 'CONTACT');
        $ct_not_recby2 = $rep->findByReceiverAndType($user2, 'CONTACT');
        
        foreach($ct_not_recby1 as $ct_not)
            if($ct_not->getSender()->getId() == $user2->getId())
                return True;
        foreach($ct_not_recby2 as $ct_not)
            if($ct_not->getSender()->getId() == $user1->getId())
                return True;
        return False;
    }
}
