<?php

namespace eclore\userBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectLabelsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectLabelsRepository extends EntityRepository
{
}
