<?php

namespace eclore\userBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

public function findByRole($role) {
    $qb = $this->_em->createQueryBuilder();
    $qb->select('a')
            ->from($this->_entityName, 'a')
            ->join('a.user', 'u')
            ->where('u.roles LIKE :roles')
            ->setParameter('roles', '%"' . $role . '"%')
            ->orderBy('u.registrationDate', 'DESC');
    return $qb->getQuery()->getResult();
}

}
