eclore\userBundle\Entity\User:
    properties:
        mobile: 
            - Regex: "/^((\+[0-9]{11})|(0[0-9]{9})|(00[0-9]{11}))$/"
        birthDate: 
            - Date: ~
            
eclore\userBundle\Entity\Image:
    properties:            
        file:
            - Image:
                minWidth: 100
                maxWidth: 1000
                minHeight: 100
                maxHeight: 1000
            
eclore\userBundle\Entity\Project:           
    getters:
        responsiblesValid:
            - "True": { message: "Les responsables doivent faire partie de l'association du projet!" }
        endDateValid:
            - "True": { message: "Le projet doit commencer avant de se finir!" }
        city:
            - NotNull: { message: "Veuillez choisir une ville" }
        required:
            - GreaterThan:
                value: 0 : { message: "Le nombre de jeunes souhaité doit être positif!" }